# Generated by Django 5.2.11 on 2026-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20),
        ),
    ]
